# Generated by Django 4.2.1 on 2023-11-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliId', models.CharField()),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
    ]
